minetest.register_tool("rangedweapons:shaft", {
	wield_scale = {x=1.9,y=1.9,z=2.5},
	description = "Shaft",
	range = 0,
	weapon_zoom = 12,
RW_powergun_capabilities = {
		power_damage = {fleshy=18,knockback=0},
		power_crit = 31,
		power_critEffc = 2.0,
		power_skill = {"",1},
		power_cooling = "rangedweapons:shaft",
		power_velocity = 60,
		power_accuracy = 100,
		power_cooldown = 2.2,
		power_projectiles = 1,
		power_durability = 12500,
		power_sound = "shaft_shot",
		power_glass_breaking = 1,
		power_door_breaking = 1,
		power_dps = 0,
		power_mob_penetration = 40,
		power_node_penetration = 0,
		power_dps = 0,
		power_consumption = 50,
		power_entity = "rangedweapons:shot_bullet",
		power_visual = "wielditem",
		power_texture = "rangedweapons:red_ray_visual",
		power_projectile_size = 0.075,
		has_sparks = 0,
		ignites_explosives = 1,
	},
	inventory_image = "rangedweapons_shaft.png",
	on_use = function(itemstack, user, pointed_thing)
rangedweapons_shoot_powergun(itemstack, user)
return itemstack
	end,
})
